apiVersion: apps/v1
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: springboot-k8s  # Name of the deployment
spec:
  replicas: 3  # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: springboot-k8s  # Label to match
  template:
    metadata:
      labels:
        app: springboot-k8s  # Label to match
    spec:
      containers:
        - name: springboot-k8s  # Name of the container
          image: springboot-k8s-coursesvc:1.0  # Image that will beused to containers in the cluster
          imagePullPolicy: IfNotPresent  # pull the image from the registry if it is not present
          ports:
            - containerPort: 8080  # Port that the container is running on in the cluster